/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

import kotlin.test.Test
import kotlin.test.assertNotNull

class MainTest {
    // @Test fun testAppHasAGreeting() {
    //     val classUnderTest = App()
    //     assertNotNull(classUnderTest.greeting, "app should have a greeting")
    // }
}
